#!/usr/bin/env bash
# Run Nginx as daemon on port 8080

# Cleanup
pkill -9 nginx
ss -K dst port 8080 2>/dev/null

# Config
cat > /etc/nginx/nginx.conf <<'EOF'
worker_processes auto;
events {}
http {
    server {
        listen 8080 reuseport;
        return 200 'Nginx operational';
    }
}
EOF

# Start
/usr/sbin/nginx -c /etc/nginx/nginx.conf -g 'user nginx;'
