#!/usr/bin/env bash
# Configures Nginx to run on port 8080 as nginx user
chmod -R 755 /etc/nginx
pkill -9 apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sed -i 's/user .*/user nginx/' /etc/nginx/nginx.conf
chown -R nginx /var/lib/nginx
nginx -g 'daemon off user nginx'
