#!/usr/bin/env bash
# Configures Nginx on port 8080 running as nginx user
pkill -9 nginx
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sed -i 's/user .*/user nginx/' /etc/nginx/nginx.conf
mkdir -p /var/run/nginx
chown nginx /var/run/nginx
nginx -g 'daemon off'
