#!/usr/bin/env bash
# Configures Nginx to run as nginx user on port 8080
pkill -9 nginx
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sed -i 's/user .*/user nginx/' /etc/nginx/nginx.conf
mkdir -p /var/run/nginx
chown nginx /var/run/nginx
nginx -g 'daemon off'
