#!/usr/bin/env bash
# Install the load balancer

# Update and upgrade system packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup original HAProxy configuration
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy for load balancing
echo '
listen 5658-lb-01
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 5822-web-02 3.83.116.84 check
    server 5822-web-01 54.237.193.140 check
' | sudo tee -a /etc/haproxy/haproxy.cfg

# Start HAProxy service
sudo service haproxy start
