#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Update package list and install Nginx
sudo apt update
sudo apt install nginx -y

# Create necessary HTML files for index and custom 404 error page
sudo touch /var/www/html/index.html
sudo touch /var/www/html/error404.html

# Add content to the HTML files
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html > /dev/null

# Configure Nginx with the custom 404 error page
printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        error_page 404 /error404.html;
        server_name _;

        location /redirect_me {
           return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
        }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Set correct file permissions for index and error pages
sudo chmod 644 /var/www/html/index.html /var/www/html/error404.html

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

